[package]
name = "function_painter_interpreter_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "interpreter",
    "drawer",
]

[dependencies]
interpreter = {path = "./interpreter"}
drawer = {path = "./drawer"}